### ISSUE TITLE
Update runtime to 3.34

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/edu.stanford.Almond#10]

**Comment by gcampax** [comment]
Hi Leandro! Thanks for the suggestion. Are you offering to work on this? 
Last I checked, we cannot easily upgrade to 3.34 because we depend on node 10, which in turn depends on python 2.7 (at build time), which is not in the runtime.

**Comment by LeandroStanger** [comment]
Shared Modules: https://github.com/flathub/flathub/wiki/App-Requirements#shared-modules

**Comment by Erick555** [comment]
@gcampax is there a reason you build own node instead of using sdk extension? https://github.com/flathub/org.freedesktop.Sdk.Extension.node10

**Comment by gcampax** [comment]
The SDK extension did not exist when this app was first packaged :) I would love to stop maintaining node and switch to the extension.
I would also help to have some documentation of how the extension is packaged, and how to use it... My experience with the gfortran and java extensions has been far from optimal.

**Comment by Erick555** [comment]
You may try below modifications in manifest

```
    "sdk-extensions" : [
        "org.freedesktop.Sdk.Extension.openjdk11",
        "org.freedesktop.Sdk.Extension.node10"
    ],
```

The add for elements that use node:

```
            "build-options":{
                "append-path": "/usr/lib/sdk/node10/bin",
                "append-ld-library-path": "/usr/lib/sdk/node10/lib",
                "env":{
                    "npm_config_nodedir": "/usr/lib/sdk/node10"
                }
```

**Comment by gcampax** [comment]
I assume I also need to call install.sh somewhere?

**Comment by Erick555** [comment]
Yeah, if you need it at runtime. You can look at instructions for openjdk extension: https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk#usage

**Comment by gcampax** [comment]
Alright, I'll look into that. I can't promise it will be fixed quickly though, so any contribution in the form of buildable PRs would be much appreciated.

**Comment by Erick555** [comment]
First attempt: https://github.com/flathub/edu.stanford.Almond/pull/11

**Comment by gcampax** [comment]
After further testing, it turns out even if the python2 / nodejs problem is solved, bazel does not build on the 3.34, due to the bundled grpc dependency, which declares `gettid` with an incompatible signature compared to glibc. This is obviously broken, but grpc is a build-system minefield (I had problems with it before) and I don't have time to figure out how to apply a patch in bazel...

Is there a timeline for the deprecation of the 3.32 runtime?
We can switch to a prebuilt tensorflow as a stopgap (x86_64 only) if EOL is imminent.

**Comment by Erick555** [comment]
Hm, but bazel was build in the PR I posted above or do you mean it's broken at runtime?

I see there are a couple of [more recent bazel releases](https://github.com/bazelbuild/bazel/releases) than 0.29.1 which is currently used so maybe updating it will fix the issue.

I also saw issues with rpc and latest glibc previously and bundling [libtirpc](https://github.com/flathub/tv.kodi.Kodi/pull/69/commits/07f429f281b58a19f5d75a95b1b75115cdea28b1) was the solution.

**Comment by Erick555** [comment]
I found this patch which may fix rpc issue in bazel: https://git.archlinux.org/svntogit/community.git/plain/trunk/grpc_rename_gettid.patch?h=packages/bazel

**Comment by gcampax** [comment]
The update to 3.34 turned out to be a lot messier than I thought - or rather, as messy as I thought it would be, before seeing someone had a made a grpc patch. Turns out convincing tensorflow to load the patched grpc was not easy, and there were other problems.
(if you're interested, details are at https://github.com/stanford-oval/almond-gnome/pull/54 )

In any case, I have a build based on 3.34 now, I'm going to test it and if all goes well it will come out as part of the 1.7.1 stable release in a couple day.s
